#/appspec.yml
# version: 0.0
# os: linux
# files:
#   - source: /
#     destination: /home/ubuntu/build
# hooks:
#   BeforeInstall:
#     - location: /BeforeInstall.sh
#       timeout: 300
#       runas: root
      
#   AfterInstall:
#     - location: scripts/after_install.sh
#       timeout: 1000
#       runas: root

#   ApplicationStart:
#     - location: scripts/start_server.sh
#       timeout: 300
#       runas: root



version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/build
permissions:
  - object: /home/ubuntu/build
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  BeforeInstall:  
    - location: /initialize.sh
      runas: ubuntu
      
  ApplicationStart:
    - location: /startapp.sh
      runas: ubuntu
