#/appspec.yml
version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/build
hooks:
  BeforeInstall:
    - location: /before_install.sh
      timeout: 300
      runas: root
      
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 1000
      runas: root

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
