# buildspec.yml
version: 0.1 # arbitrary version name for management
phases:
   install:
     commands:
       - npm install
   build:
     commands:
       - npm run build
       - npm run export
 # follow npm command declared in package.json file.
 
 
 
artifacts: # Specifies the output artifacts of CodeBuild stage.
   files:     - '**/*'
   base-directory: 'dist'   # by setting base-directory and files like this, all files in the dist directory become output artifacts.
